<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 7/30/2019
 * Time: 1:56 PM
 */
namespace Modules\Catering\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Catering\Models\Catering;
use Modules\Catering\Models\CateringTerm;
use Modules\Catering\Models\CateringTranslation;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\Core\Models\Attributes;
use Modules\Location\Models\Location;

class CateringController extends AdminController
{
    protected $catering;
    protected $catering_translation;
    protected $catering_term;
    protected $attributes;
    protected $location;

    public function __construct()
    {
        parent::__construct();
        $this->setActiveMenu('admin/module/catering');
        $this->catering = Catering::class;
        $this->catering_translation = CateringTranslation::class;
        $this->catering_term = CateringTerm::class;
        $this->attributes = Attributes::class;
        $this->location = Location::class;
    }

    public function callAction($method, $parameters)
    {
        if (!Catering::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('catering_view');
        $query = $this->catering::query();
        $query->orderBy('id', 'desc');
        if (!empty($s = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $s . '%');
            $query->orderBy('title', 'asc');
        }
        if ($this->hasPermission('catering_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('create_user', $author);
            }
        } else {
            $query->where('create_user', Auth::id());
        }
        $data = [
            'rows'              => $query->with(['author'])->paginate(20),
            'catering_manage_others' => $this->hasPermission('catering_manage_others'),
            'breadcrumbs'       => [
                [
                    'name' => __('Caterings'),
                    'url'  => 'admin/module/tour'
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Catering Management")
        ];
        return view('Catering::admin.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('catering_view');
        $query = $this->catering::onlyTrashed();
        $query->orderBy('id', 'desc');
        if (!empty($s = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $s . '%');
            $query->orderBy('title', 'asc');
        }
        if ($this->hasPermission('catering_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('create_user', $author);
            }
        } else {
            $query->where('create_user', Auth::id());
        }
        $data = [
            'rows'              => $query->with(['author'])->paginate(20),
            'catering_manage_others' => $this->hasPermission('catering_manage_others'),
            'recovery'          => 1,
            'breadcrumbs'       => [
                [
                    'name' => __('Caterings'),
                    'url'  => 'admin/module/tour'
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Recovery Catering Management")
        ];
        return view('Catering::admin.index', $data);
    }

    public function create(Request $request)
    {
        $this->checkPermission('catering_create');
        $row = new $this->catering();
        $row->fill([
            'status' => 'publish'
        ]);
        $data = [
            'row'          => $row,
            'attributes'   => $this->attributes::where('service', 'catering')->get(),
            'catering_location' => $this->location::where('status', 'publish')->get()->toTree(),
            'translation'  => new $this->catering_translation(),
            'breadcrumbs'  => [
                [
                    'name' => __('Caterings'),
                    'url'  => 'admin/module/catering'
                ],
                [
                    'name'  => __('Add Catering'),
                    'class' => 'active'
                ],
            ],
            'page_title'   => __("Add new Catering")
        ];
        return view('Catering::admin.detail', $data);
    }

    public function edit(Request $request, $id)
    {
        $this->checkPermission('catering_update');
        $row = $this->catering::find($id);
        if (empty($row)) {
            return redirect(route('catering.admin.index'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        if (!$this->hasPermission('catering_manage_others')) {
            if ($row->create_user != Auth::id()) {
                return redirect(route('catering.admin.index'));
            }
        }
        $data = [
            'row'               => $row,
            'translation'       => $translation,
            "selected_terms"    => $row->terms->pluck('term_id'),
            'attributes'        => $this->attributes::where('service', 'catering')->get(),
            'catering_location'      => $this->location::where('status', 'publish')->get()->toTree(),
            'enable_multi_lang' => true,
            'breadcrumbs'       => [
                [
                    'name' => __('Caterings'),
                    'url'  => 'admin/module/catering'
                ],
                [
                    'name'  => __('Edit Catering'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Edit: :name", ['name' => $row->title])
        ];
        return view('Catering::admin.detail', $data);
    }

    public function store(Request $request, $id)
    {

        if ($id > 0) {
            $this->checkPermission('catering_update');
            $row = $this->catering::find($id);
            if (empty($row)) {
                return redirect(route('catering.admin.index'));
            }
            if ($row->create_user != Auth::id() and !$this->hasPermission('catering_manage_others')) {
                return redirect(route('catering.admin.index'));
            }
        } else {
            $this->checkPermission('catering_create');
            $row = new $this->catering();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'status',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'number',
            'price',
            'sale_price',
            'passenger',
            'gear',
            'baggage',
            'door',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'enable_service_fee',
            'service_fee',
            'min_day_before_booking',
            'min_day_stays',
        ];
        if ($this->hasPermission('catering_manage_others')) {
            $dataKeys[] = 'create_user';
        }
        $row->fillByAttr($dataKeys, $request->input());
        if ($request->input('slug')) {
            $row->slug = $request->input('slug');
        }
        $res = $row->saveOriginOrTranslation($request->input('lang'), true);
        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }
            if ($id > 0) {
                event(new UpdatedServiceEvent($row));
                return back()->with('success', __('Catering updated'));
            } else {
                event(new CreatedServicesEvent($row));
                return redirect(route('catering.admin.edit', $row->id))->with('success', __('Catering created'));
            }
        }
    }

    public function saveTerms($row, $request)
    {
        $this->checkPermission('catering_manage_attributes');
        if (empty($request->input('terms'))) {
            $this->catering_term::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->catering_term::firstOrCreate([
                    'term_id'   => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->catering_term::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function bulkEdit(Request $request)
    {

        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action) {
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->catering::where("id", $id);
                    if (!$this->hasPermission('catering_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('catering_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->delete();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "permanently_delete":
                foreach ($ids as $id) {
                    $query = $this->catering::where("id", $id);
                    if (!$this->hasPermission('catering_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('catering_delete');
                    }
                    $row = $query->withTrashed()->first();
                    if ($row) {
                        $row->forceDelete();
                    }
                }
                return redirect()->back()->with('success', __('Permanently delete success!'));
                break;
            case "recovery":
                foreach ($ids as $id) {
                    $query = $this->catering::withTrashed()->where("id", $id);
                    if (!$this->hasPermission('catering_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('catering_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->restore();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Recovery success!'));
                break;
            case "clone":
                $this->checkPermission('catering_create');
                foreach ($ids as $id) {
                    (new $this->catering())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->catering::where("id", $id);
                    if (!$this->hasPermission('catering_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('catering_update');
                    }
                    $row = $query->first();
                    $row->status = $action;
                    $row->save();
                    event(new UpdatedServiceEvent($row));
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }

    public function getForSelect2(Request $request)
    {
        $pre_selected = $request->query('pre_selected');
        $selected = $request->query('selected');
        if ($pre_selected && $selected) {
            if (is_array($selected)) {
                $items = $this->catering::select('id', 'title as text')->whereIn('id', $selected)->take(50)->get();
                return $this->sendSuccess([
                    'items' => $items
                ]);
            } else {
                $item = $this->catering::find($selected);
            }
            if (empty($item)) {
                return $this->sendSuccess([
                    'text' => ''
                ]);
            } else {
                return $this->sendSuccess([
                    'text' => $item->name
                ]);
            }
        }
        $q = $request->query('q');
        $query = $this->catering::select('id', 'title as text')->where("status", "publish");
        if ($q) {
            $query->where('title', 'like', '%' . $q . '%');
        }
        $res = $query->orderBy('id', 'desc')->limit(20)->get();
        return $this->sendSuccess([
            'results' => $res
        ]);
    }
}

