<?php
namespace Modules\Catering\Controllers;

use App\Notifications\AdminChannelServices;
use Modules\Booking\Events\BookingUpdatedEvent;
use Modules\Booking\Models\Enquiry;
use Modules\Catering\Models\Catering;
use Modules\Catering\Models\CateringTerm;
use Modules\Catering\Models\CateringTranslation;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Booking\Models\Booking;

class ManageCateringController extends FrontendController
{
    protected $cateringClass;
    protected $cateringTranslationClass;
    protected $cateringTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    protected $enquiryClass;

    public function __construct()
    {
        parent::__construct();
        $this->cateringClass = Catering::class;
        $this->cateringTranslationClass = CateringTranslation::class;
        $this->cateringTermClass = CateringTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->bookingClass = Booking::class;
        $this->enquiryClass = Enquiry::class;
    }

    public function callAction($method, $parameters)
    {
        if(!Catering::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function manageCatering(Request $request)
    {
        $this->checkPermission('catering_view');
        $user_id = Auth::id();
        $list_tour = $this->cateringClass::where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Caterings'),
                    'url'  => route('catering.vendor.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Manage Caterings"),
        ];
        return view('Catering::frontend.manageCatering.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('catering_view');
        $user_id = Auth::id();
        $list_tour = $this->cateringClass::onlyTrashed()->where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'recovery'           => 1,
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Caterings'),
                    'url'  => route('catering.vendor.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Recovery Caterings"),
        ];
        return view('Catering::frontend.manageCatering.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('catering_delete');
        $user_id = Auth::id();
        $query = $this->cateringClass::onlyTrashed()->where("create_user", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
            event(new UpdatedServiceEvent($query));

        }
        return redirect(route('catering.vendor.recovery'))->with('success', __('Restore catering success!'));
    }

    public function createCatering(Request $request)
    {
        $this->checkPermission('catering_create');
        $row = new $this->cateringClass();
        $data = [
            'row'           => $row,
            'translation' => new $this->cateringTranslationClass(),
            'catering_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'catering')->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Caterings'),
                    'url'  => route('catering.vendor.index')
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Create Caterings"),
        ];
        return view('Catering::frontend.manageCatering.detail', $data);
    }


    public function store( Request $request, $id ){
        if($id>0){
            $this->checkPermission('catering_update');
            $row = $this->cateringClass::find($id);
            if (empty($row)) {
                return redirect(route('catering.vendor.index'));
            }

            if($row->create_user != Auth::id() and !$this->hasPermission('catering_manage_others'))
            {
                return redirect(route('catering.vendor.index'));
            }
        }else{
            $this->checkPermission('catering_create');
            $row = new $this->cateringClass();
            $row->status = "publish";
            if(setting_item("catering_vendor_create_service_must_approved_by_admin", 0)){
                $row->status = "pending";
            }
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'number',
            'price',
            'sale_price',
            'passenger',
            'gear',
            'baggage',
            'door',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'enable_service_fee',
            'service_fee',
            'min_day_before_booking',
            'min_day_stays',
        ];
        if($this->hasPermission('catering_manage_others')){
            $dataKeys[] = 'create_user';
        }

        $row->fillByAttr($dataKeys,$request->input());

        $res = $row->saveOriginOrTranslation($request->input('lang'),true);

        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }

            if($id > 0 ){
                event(new UpdatedServiceEvent($row));
                return back()->with('success',  __('Catering updated') );
            }else{
                event(new CreatedServicesEvent($row));
                return redirect(route('catering.vendor.edit',['id'=>$row->id]))->with('success', __('Catering created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->cateringTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->cateringTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->cateringTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function editCatering(Request $request, $id)
    {
        $this->checkPermission('catering_update');
        $user_id = Auth::id();
        $row = $this->cateringClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('catering.vendor.index'))->with('warning', __('Catering not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'           => $row,
            'catering_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'catering')->get(),
            "selected_terms" => $row->terms->pluck('term_id'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Caterings'),
                    'url'  => route('catering.vendor.index')
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Edit Caterings"),
        ];
        return view('Catering::frontend.manageCatering.detail', $data);
    }

    public function deleteCatering($id)
    {
        $this->checkPermission('catering_delete');
        $user_id = Auth::id();
        if(\request()->query('permanently_delete')){
            $query = $this->cateringClass::where("create_user", $user_id)->where("id", $id)->withTrashed()->first();
            if (!empty($query)) {
                $query->forceDelete();
            }
        }else {
            $query = $this->cateringClass::where("create_user", $user_id)->where("id", $id)->first();
            if (!empty($query)) {
                $query->delete();
                event(new UpdatedServiceEvent($query));
            }
        }
        return redirect(route('catering.vendor.index'))->with('success', __('Delete catering success!'));
    }

    public function bulkEditCatering($id , Request $request){
        $this->checkPermission('catering_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->cateringClass::where("create_user", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if(empty($query)){
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action){
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                break;
        }
        $query->save();
        event(new UpdatedServiceEvent($query));

        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReportBulkEdit($booking_id , Request $request){
        $status = $request->input('status');
        if (!empty(setting_item("catering_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if(!empty($item)){
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();
                event(new BookingUpdatedEvent($item));
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }
}

